swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /auth/login:
    post:
      tags:
      - auth
      description: Logs user into the system
      operationId: AuthController.Login
      parameters:
      - in: body
        name: body
        description: body for user
        required: true
        schema:
          $ref: '#/definitions/models.LoginDto'
      responses:
        "200":
          description: '{int} body models.User'
        "400":
          description: Login failed
  /auth/register:
    post:
      tags:
      - auth
      description: Register users
      operationId: AuthController.Register
      parameters:
      - in: body
        name: body
        description: body for user content
        required: true
        schema:
          $ref: '#/definitions/models.LoginDto'
      responses:
        "200":
          description: '{int} body models.User'
        "403":
          description: body is empty
  /categories/:
    get:
      tags:
      - categories
      description: get category
      operationId: CategoryController.GetAll
      parameters:
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Category'
        "500":
          description: Internal Server Error
  /categories/{id}:
    get:
      tags:
      - categories
      description: get category by id
      operationId: CategoryController.Get
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Category'
        "403":
          description: :id is empty
  /user/:
    get:
      tags:
      - user
      description: Get all users
      operationId: UserController.Get all users
      responses:
        "200":
          description: '{int} body []*models.User'
        "403":
          description: body is empty
definitions:
  models.Base:
    title: Base
    type: object
    properties:
      ID:
        $ref: '#/definitions/uuid.UUID'
      created_at:
        type: string
        format: datetime
      deleted_at:
        type: string
        format: datetime
      updated_at:
        type: string
        format: datetime
  models.Category:
    title: Category
    type: object
    properties:
      ID:
        $ref: '#/definitions/uuid.UUID'
      created_at:
        type: string
        format: datetime
      deleted_at:
        type: string
        format: datetime
      title:
        type: string
      updated_at:
        type: string
        format: datetime
  models.LoginDto:
    title: LoginDto
    type: object
    properties:
      password:
        type: string
      username:
        type: string
  uuid.UUID:
    title: UUID
    type: object
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    description: Authorization token
    name: Authorization
    in: header
security:
- ApiKeyAuth: []
